### ISSUE TITLE
i need your help sir

### ISSUE THREAD

**Issue by ORNATEit** [engacs/Autobackup-databse-on-GoogleDrive#1]
Fatal error: Uncaught Google_AuthException: Error fetching OAuth2 access token, message: 'invalid_grant' in E:\xampp\htdocs\1\Autobackup-databse-to-GoogleDrive-master\google-api-php-client\src\auth\Google_OAuth2.php:115 Stack trace: #0 E:\xampp\htdocs\1\Autobackup-databse-to-GoogleDrive-master\google-api-php-client\src\Google_Client.php(127): Google_OAuth2->authenticate(Array, 'https://account...') #1 E:\xampp\htdocs\1\Autobackup-databse-to-GoogleDrive-master\backuptogoogledrive.php(104): Google_Client->authenticate('https://account...') #2 {main} thrown in E:\xampp\htdocs\1\Autobackup-databse-to-GoogleDrive-master\google-api-php-client\src\auth\Google_OAuth2.php on line 115

**Comment by engacs** [comment]
i  think you have a problem with the OAuth2, you need to create
Google Drive Auth
Get this from the Google APIs Console https://code.google.com/apis/console/

// Google Drive Client ID
  $clientId = "";
 // Google Drive Client Secret
  $clientSecret = "";

Then you have to get  Google Drive authentication credentials both Client ID and Client Secret,
then open the file **getauthcode.php** on the browser to copy the Provided URL to authenticate your application
